### ISSUE TITLE
googleCalendargoogleCalendar@javahelps.com  gcalendar is not authorised

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-desklets#737]
```
 * Desklet version/Build date:  Updated on 2021-12-11 00:07:32
 * Cinnamon version:  5.0.7
 * Distribution: Arch 5.15.7
 * Graphics hardware *and* driver used:  ATI Radeon
 * Snippet or attachment of ~/.cinnamon/glass.log
error t=2021-12-14T10:27:26Z JSON.parse: expected double-quoted property name at line 110 column 3 of the JSON data
error t=2021-12-14T10:27:26Z Failed to parse template file for googleCalendar@javahelps.com
warning t=2021-12-14T10:27:26Z upgrade failed for googleCalendar@javahelps.com: falling back to previous settings
info t=2021-12-14T10:27:26Z Loaded desklet googleCalendar@javahelps.com in 35 ms
 * Snippet or attachment of ~/.xsession-errors
error t=2021-12-14T10:27:26Z JSON.parse: expected double-quoted property name at line 110 column 3 of the JSON data
error t=2021-12-14T10:27:26Z Failed to parse template file for googleCalendar@javahelps.com
warning t=2021-12-14T10:27:26Z upgrade failed for googleCalendar@javahelps.com: falling back to previous settings
info t=2021-12-14T10:27:26Z Loaded desklet googleCalendar@javahelps.com in 35 ms

sh 831 [1] % gcalendar
Traceback (most recent call last):
  File "/usr/bin/gcalendar", line 33, in <module>
    sys.exit(load_entry_point('gcalendar==0.4.1', 'console_scripts', 'gcalendar')())
  File "/usr/bin/gcalendar", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for gcalendar

<!-- Author list: https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/.github/CODEOWNERS -->

**Notify author of desklet**
@javahelps.com

**Issue**
Display:  gcalendar is not authorised
excecute gcalendar

**Steps to reproduce**
excecute gcalendar
In Configure, all previous items empty, nothing can be loaded.

**Expected behaviour**
Display calendar items.

**Other information**
Yesterday, 13 december 2021, there was an major update of Python packages. Prior to this the calendar was displaying normally.

**Comment by Padre2** [comment]
Issue solved after reinstalling `gcalendar`
