### ISSUE TITLE
googleCalendargoogleCalendar@javahelps.com gcalendar is not authorised

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-spices-desklets#743]
```
 Desklet version/Build date:  Updated on 2021-12-11 00:07:32
 * Cinnamon version:  5.0.7
 * Distribution: Arch 5.15.7
 * Graphics hardware *and* driver used:  ATI Radeon
 * Snippet or attachment of ~/.cinnamon/glass.log
`error t=2021-12-19T10:12:23Z Failed to parse template file for googleCalendar@javahelps.com
warning t=2021-12-19T10:12:23Z upgrade failed for googleCalendar@javahelps.com: falling back to previous settings
info t=2021-12-19T10:12:23Z Loaded desklet googleCalendar@javahelps.com in 246 ms`

Execute gcalendar
```zsh 861 [1] % gcalendar       
Traceback (most recent call last):
  File "/usr/bin/gcalendar", line 33, in <module>
    sys.exit(load_entry_point('gcalendar==0.4.1', 'console_scripts', 'gcalendar')())
  File "/usr/bin/gcalendar", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/gcalendar/__main__.py", line 32, in <module>
    from gcalendar.gcalendar import GCalendar
  File "/usr/lib/python3.10/site-packages/gcalendar/gcalendar.py", line 22, in <module>
    from googleapiclient import discovery
  File "/usr/lib/python3.10/site-packages/googleapiclient/discovery.py", line 63, in <module>
    from googleapiclient.http import build_http
  File "/usr/lib/python3.10/site-packages/googleapiclient/http.py", line 61, in <module>
    from googleapiclient.model import JsonModel
  File "/usr/lib/python3.10/site-packages/googleapiclient/model.py", line 29, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 559, in _build_master
    ws = cls()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 552, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 608, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2063, in find_on_path
    for dist in factory(fullpath):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2128, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2591, in from_location
    )._reload_version()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2989, in _reload_version
    md_version = self._get_version()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2770, in _get_version
    version = _version_from_file(lines)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2554, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2765, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1417, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1407, in get_metadata
    value = self._get(path)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1611, in _get
    with open(path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.10/site-packages/google_api_core-2.3.2-py3.10.egg-info/PKG-INFO'
 ```

**Notify author of desklet**
@javahelps.com

**Issue**
Display:  gcalendar is not authorised
excecute gcalendar

**Steps to reproduce**
excecute gcalendar

**Expected behaviour**
Calendar displayed

**Other information**
Yesterday, 18 december 2021, there was another update of Python packages. Prior to this the calendar was displaying normally.
An attempt to reinstall galcalendar failed, ending with the following:
```PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.10/site-packages/google_api_core-2.3.2-py3.10.egg-info/PKG-INFO'
==> ERROR: A failure occurred in package().
    Aborting...
error making: gcalendar
yay -S gcalendar  9.37s user 7.82s system 48% cpu 35.450 total

**Comment by Padre2** [comment]
Another Python packeage update and the calendar is displaying normally again, however with errors in the looking glass log:
`error t=2021-12-20T10:12:12Z JSON.parse: expected double-quoted property name at line 110 column 3 of the JSON data
error t=2021-12-20T10:12:12Z Failed to parse template file for googleCalendar@javahelps.com
warning t=2021-12-20T10:12:12Z upgrade failed for googleCalendar@javahelps.com: falling back to previous settings
info t=2021-12-20T10:12:12Z Loaded desklet googleCalendar@javahelps.com in 44 ms`

**Comment by Padre2** [comment]
Applied update of 2021-12-28 06:48:21 and no more error messages in Looking Glass and calendar displays normally, thank you.
